config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  get 'carty/show'

  root 'page#index'
  get '/about', to: 'page#about'
  match '/contact', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  
  resources :users, except: [:index]
  
  resources :reviews

  post  'reviews/new/:id', to: 'reviews#new'
  get   'reviews/new/:id', to: 'reviews#new'
  post  'reviews/displays/:id', to: 'reviews#displays'
  get   'reviews/displays/:id', to: 'reviews#displays'

  resources :carts
  get 'errors/routing'

  
  controller :sessions do
    get  'login' => :new        # login_path
    post 'login' => :create
    get 'logout' => :destroy    # logout_path
  end

  
  
  get 'products/search', to: 'products#search'
  post 'products/search', to: 'products#search'

  

  resources :categories
  resources :products do
    collection do
      get :search
    end
  end
  resources :brands
  resources :carts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match '*a', to: 'errors#routing',   via: [:get, :post]
    
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  
  before_destroy :check_if_last

  private

  def check_if_last
    if (AdminUser.all.count == 1)
      errors.add(:base, "Cannot delete last admin")
      return false
    end
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  extend FriendlyId
  has_many :products

  friendly_id :name, use: [:slugged, :finders]
  
  validates :name, :presence => { :message => "cannot be blank ..."}, 
                   :length => {:in => 2..35, :message => "must be between two and thirty five characters"}
  
  validates :description, :presence => { :message => "cannot be blank ..."},
                          :length => {:maximum => 2000, :message => "maximum length 2000 characters"} 
  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_products
  has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ActiveRecord::Base
	extend FriendlyId
	has_many :products

	friendly_id :name, use: [:slugged, :finders]
	
	validates :name, :presence => { :message => "cannot be blank"}, 
                   :length => {:in => 2..35, :message => "must be between two and thirty five characters"}
  
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "vtr_andrioli@hotmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: [:slugged, :finders]

	searchable do 
		text :name
		text :description
	end
	ratyrate_rateable 'rating'
	
	scope :featured, -> { where(highlighted: true) }
	
  
  belongs_to :category
	belongs_to :brand
	has_many :images, class_name: "ProductImage", :dependent => :destroy
	has_many :videos, class_name: "ProductVideo", :dependent => :destroy
	
	has_and_belongs_to_many(:associated_products,
	 :class_name => "Product",
   :join_table => "product_connections",
   :foreign_key => "product_a_id",
   :association_foreign_key => "product_b_id")
	
	has_many :cart_productss
	has_many :carts, through: :cart_products

	accepts_nested_attributes_for :images, :allow_destroy => true
  accepts_nested_attributes_for :videos, :allow_destroy => true
  accepts_nested_attributes_for :associated_products, :allow_destroy => true
  
  validates :category_id, :presence => { :message => "cannot be blank"}
	
	validates :name, :presence => { :message => "cannot be blank"},
	                 :length => {:in => 2..35, :message => "must be between two and thirty five characters"}
  
  validates :price, :presence => { :message => "cannot be blank"},
                    :numericality => {:greater_than_or_equal_to => 0, :allow_blank => false, :message => "must be a positive value"}

  validates :description, :presence => { :message => "cannot be blank"},
                          :length => {:maximum => 2000, :message => "maximum length 2000 characters"} 
  

  	def self.simple_search(search_string)
		self.where("name = ?", search_string)
	end

end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  mount_uploader :url, ProductImageUploader
  
	belongs_to :product
end

app/models/product_video.rb
class ProductVideo < ActiveRecord::Base
  mount_uploader :file_url, ProductVideoUploader
  mount_uploader :still, ProductVideoStillUploader
  
	belongs_to :product
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :carts
  has_many :reviews
  
  validates :name, presence: true, uniqueness: true
  validates :email, uniqueness: true, email_format: { message: "That is not a valid email address." }
  
  ratyrate_rater 
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "#{@user.name}: you have successfully registered."
    else
      render action: 'new'
    end
  end


  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "#{@user.name}'s details were successfully updated."
    else
      render action: 'edit'
    end
  end

  def destroy
    session[:user_id] = nil
    @user.destroy
    
    redirect_to root_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :email)
    end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/carty_helper.rb
module CartyHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form1">


  <%= form_for(@user) do |f| %>
  
  <div class="row featurette">
  <div class="col-md-7">
    <div class="form-group">
      <%= f.label :name, 'Name:',  :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :name, :autofocus => true, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :email, 'Email:',  :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :email, :autofocus => true, :class => "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password, 'Password:',  :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.password_field :password , size: 40, :class => "form-control" %>
      </div>
    </div>
  
    <div class="form-group">
      <%= f.label :password_confirmation, 'Confirm:',  :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.password_field :password_confirmation, size: 40, :class => "form-control" %>
      </div>
    </div>
  
    <div class="actions">
    <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit "Update User", :class=> "btn btn-primary ", :class=> "btn btn-primary " %>
          </div>
    </div>
  </div>
  </div>
  <% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render "/error_messages", 
			:message_header => "Cannot save: ", 
			:target => @user %> 

<div class="page-header m-t-1">
	<h1><small>New Account</small></h1>
</div>

<div class="row featurette">
  <div class="col-md-7">

  <%= form_for(@user, :html => {:class => 'form-horizontal', :id => 'form', :data => {:toggle => "validator"} } ) do |f| %>

    <div class="form-group">
      <%= f.label :name, 'Name:',  :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :name,  :autofocus => true, :class => "form-control", :required => "" %>
        <div class="help-block with-errors"></div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :email, 'Email:',  :class =>"col-sm-2 control-label"%>
      <div class="col-sm-6">
          <%= f.text_field :email, :type=>"email", :autofocus => true, :class => "form-control", :id => "inputEmail", :data => {:error => "Email is not valid"}, :required => ""  %>
          <p class="help-block with-errors"></p>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password, 'Password:',  :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.password_field :password, :type => "password", size: 40, :class => "form-control", :id => "inputPassword", :data => { :minlength => "6"}, :required => "" %>
        <p class="help-block">Minimum of 6 characters</p>
      </div>
    </div>
  
    <div class="form-group">
      <%= f.label :password_confirmation, 'Confirm:',  :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.password_field :password_confirmation, :type => "password", size: 40, :class => "form-control", :id => "inputPasswordConfirm", :data => { :match => "#inputPassword", :'match-error' => "Whoops, these don't match"} %>
         <div class="help-block with-errors"></div>
      </div>
    </div>
  
    <div class="actions">
    <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit "Submit", :class=> "btn btn-primary ", :class=> "btn btn-primary " %>
          </div>
    </div>
  </div>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> | 
<%= link_to 'Delete account', @user, method: :delete, data: { confirm: 'Are you sure you want to delete your account?' } %>