config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'
  get 'carty/show'

  root 'page#index'
  get '/about', to: 'page#about'
  match '/contact', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  
  resources :users, except: [:index]
  
  resources :reviews

  post  'reviews/new/:id', to: 'reviews#new'
  get   'reviews/new/:id', to: 'reviews#new'
  post  'reviews/displays/:id', to: 'reviews#displays'
  get   'reviews/displays/:id', to: 'reviews#displays'

  resources :carts
  get 'errors/routing'

  
  controller :sessions do
    get  'login' => :new        # login_path
    post 'login' => :create
    get 'logout' => :destroy    # logout_path
  end

  
  
  get 'products/search', to: 'products#search'
  post 'products/search', to: 'products#search'

  

  resources :categories
  resources :products do
    collection do
      get :search
    end
  end
  resources :brands
  resources :carts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match '*a', to: 'errors#routing',   via: [:get, :post]
    
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  
  before_destroy :check_if_last

  private

  def check_if_last
    if (AdminUser.all.count == 1)
      errors.add(:base, "Cannot delete last admin")
      return false
    end
  end
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  extend FriendlyId
  has_many :products

  friendly_id :name, use: [:slugged, :finders]
  
  validates :name, :presence => { :message => "cannot be blank ..."}, 
                   :length => {:in => 2..35, :message => "must be between two and thirty five characters"}
  
  validates :description, :presence => { :message => "cannot be blank ..."},
                          :length => {:maximum => 2000, :message => "maximum length 2000 characters"} 
  
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_products
  has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ActiveRecord::Base
	extend FriendlyId
	has_many :products

	friendly_id :name, use: [:slugged, :finders]
	
	validates :name, :presence => { :message => "cannot be blank"}, 
                   :length => {:in => 2..35, :message => "must be between two and thirty five characters"}
  
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "vtr_andrioli@hotmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: [:slugged, :finders]

	searchable do 
		text :name
		text :description
	end
	ratyrate_rateable 'rating'
	
	scope :featured, -> { where(highlighted: true) }
	
  
  belongs_to :category
	belongs_to :brand
	has_many :images, class_name: "ProductImage", :dependent => :destroy
	has_many :videos, class_name: "ProductVideo", :dependent => :destroy
	
	has_and_belongs_to_many(:associated_products,
	 :class_name => "Product",
   :join_table => "product_connections",
   :foreign_key => "product_a_id",
   :association_foreign_key => "product_b_id")
	
	has_many :cart_productss
	has_many :carts, through: :cart_products

	accepts_nested_attributes_for :images, :allow_destroy => true
  accepts_nested_attributes_for :videos, :allow_destroy => true
  accepts_nested_attributes_for :associated_products, :allow_destroy => true
  
  validates :category_id, :presence => { :message => "cannot be blank"}
	
	validates :name, :presence => { :message => "cannot be blank"},
	                 :length => {:in => 2..35, :message => "must be between two and thirty five characters"}
  
  validates :price, :presence => { :message => "cannot be blank"},
                    :numericality => {:greater_than_or_equal_to => 0, :allow_blank => false, :message => "must be a positive value"}

  validates :description, :presence => { :message => "cannot be blank"},
                          :length => {:maximum => 2000, :message => "maximum length 2000 characters"} 
  

  	def self.simple_search(search_string)
		self.where("name = ?", search_string)
	end

end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  mount_uploader :url, ProductImageUploader
  
	belongs_to :product
end

app/models/product_video.rb
class ProductVideo < ActiveRecord::Base
  mount_uploader :file_url, ProductVideoUploader
  mount_uploader :still, ProductVideoStillUploader
  
	belongs_to :product
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :carts
  has_many :reviews
  
  validates :name, presence: true, uniqueness: true
  validates :email, uniqueness: true, email_format: { message: "That is not a valid email address." }
  
  ratyrate_rater 
  has_secure_password
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/carty_helper.rb
module CartyHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<ul class="nav navbar-nav text-muted">
	      	<li class="nav"> <%= link_to "About us", about_path %> </li>				
			<li class="nav"> <%= link_to "Contact Us", contact_path %> </li>
			<li class="nav"><p> <%= the_date %> </p> </li>
	    </ul>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container">   
		<ul class="nav navbar-nav navbar-left">
			<li class="nav"> <%= link_to "Home", root_path %></li>	
			<li><div><%= render(:partial=>'/search',:locals=> { :my_path => "/products/search" })%></div></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<% if not logged_in? %>			
				<li> <%= link_to "Log In", login_path %> </li>				
				<li> <%= link_to "Register", new_user_path %> </li>	
			<% else %>
				<li> <%= link_to @user.email, user_path(@user) %> </li>
				<li> <%= link_to "Logout", logout_path %> </li>
			<% end %>
		</ul>
  	
  	</div>
</nav>

		<!--
				<div id="cart-top" >
					
					<% if session[:cart_id] %>
					<div id="cart_active" >
						<%= render(:partial => '/display_cart' ) %>
					</div>	
					<% end %>
				</div>
		-->	

app/views/layouts/_mainpage.html.erb
<div class="container">
	<%= yield %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<title>Silver</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
</head>
<body>
	<div id="main-div">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6&appId=351023588343022";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>


		<%= render "layouts/header"%>
		<%= render "layouts/mainpage"%>
		<!--<%= render "layouts/footer" %>-->

    <script type="text/javascript">
      $('#form').validator()
    </script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-77235912-1', 'auto');
      ga('send', 'pageview');

    </script>

    <script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: 'adfe6867-6b40-4455-ad17-6960803076cf', f: true }); done = true; } }; })();</script>

	</div>
</body>
</html>

app/views/page/about.html.erb
<div class="page-header m-t-1">
	<h1><small>About Us</small></h1>
</div>

<div class="row featurette">
    <div class="col-md-7">
        <h2 class="featurette-heading">UK's Lowest Prices. <span class="text-muted">It'll blow your mind.</span></h2>
        <p> Pay monthly is based on new connections on selected networks on 4G tariffs. UK's Lowest Price correct at time of print and it applies to published prices, where the handset is in stock and available for immediate purchase and dispatch. Excludes all online retailers without high street presence and other promotional offers. UK's Lowest Price on pay as you go and SIM free correct at time of print and it applies to published prices, where the handset is in stock and available for immediate purchase and dispatch. </p>
        </div>
    <div class="col-md-5">
        <%= image_tag("/assets/phone.jpg", :alt => "phone", :class=>'featurette-image img-responsive center-block') %>
    </div>
</div>

app/views/page/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to Silver Phones</h1>
    <p>A marketplace for phones, tablets, and accessories.</p>
    <br/>	
    <%= link_to "All Products ->", products_path, :class => "btn btn-primary text-center" %>
  </div>
</div>

<div class="page-header m-t-1">
	<h1><small>Featured</small></h1>
</div>

<div class="row featurette">	
		<ul class="list-inline center-block text-center" style="margin-bottom: 100px;">
			
			<% @products.each do |product| %>
				<li>
					<% if not product.images.blank? %>
					        <div class="main-title"><%= link_to (image_tag product.images.first.url, :size => "250x300"), product %> </div>
					<% else %>
					        <%= link_to (image_tag("no-image.jpg", :size => "250x300")), product %>
					<% end %>
	
					<div class="main-title" style="text-align: left;"> <%= link_to (product.name), product %> </div>
					<div class="main-title" style="text-align: left;"> <%= product.price %> </div>
					<%= link_to "Shop Now", product, :class => "btn btn-primary" %>
				</li>
			
			<% end %>
		</ul>
</div>